
CREATE DATABASE IF NOT EXISTS PracticaIPS;
USE PracticaIPS;

DROP TABLE IF EXISTS Matricula;
DROP TABLE IF EXISTS Asignatura;
DROP TABLE IF EXISTS Alumno;

CREATE TABLE IF NOT EXISTS Alumno (
    NumMat INT NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    Apellido1 VARCHAR(255) NOT NULL,
    Apellido2 VARCHAR(255) NOT NULL,
    Curso VARCHAR(255) NOT NULL,
    Fecha_de_Nacimiento DATE NOT NULL,
    PRIMARY KEY (NumMat)
);

CREATE TABLE IF NOT EXISTS Asignatura (
    Codigo INT NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    PRIMARY KEY (Codigo)
);

CREATE TABLE IF NOT EXISTS Matricula (
    FK_NumMat INT NOT NULL,
    FK_Codigo INT NOT NULL,
    PRIMARY KEY (FK_NumMat, FK_Codigo),
    FOREIGN KEY (FK_NumMat) REFERENCES Alumno(NumMat) ON DELETE CASCADE,
    FOREIGN KEY (FK_Codigo) REFERENCES Asignatura(Codigo) ON DELETE CASCADE
);

