//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainRelationship DiagramaWebTieneEntidad
	/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("b20186c3-98c3-4932-a9f5-9c00ae76b0ce")]
	public partial class DiagramaWebTieneEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// DiagramaWebTieneEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xb20186c3, 0x98c3, 0x4932, 0xa9, 0xf5, 0x9c, 0x00, 0xae, 0x76, 0xb0, 0xce);
	
				
		/// <summary>
		/// Constructor
		/// Creates a DiagramaWebTieneEntidad link in the same Partition as the given DiagramaWeb
		/// </summary>
		/// <param name="source">DiagramaWeb to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public DiagramaWebTieneEntidad(DiagramaWeb source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(DiagramaWebTieneEntidad.DiagramaWebDomainRoleId, source), new DslModeling::RoleAssignment(DiagramaWebTieneEntidad.EntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DiagramaWebTieneEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DiagramaWebTieneEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DiagramaWebTieneEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DiagramaWebTieneEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region DiagramaWeb domain role code
		
		/// <summary>
		/// DiagramaWeb domain role Id.
		/// </summary>
		public static readonly global::System.Guid DiagramaWebDomainRoleId = new global::System.Guid(0xf329662f, 0x0004, 0x4d33, 0xb8, 0xfd, 0xc3, 0x20, 0xf6, 0xb0, 0x70, 0xaa);
		
		/// <summary>
		/// DomainRole DiagramaWeb
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWeb
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/DiagramaWeb.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/DiagramaWeb.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/DiagramaWeb.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("f329662f-0004-4d33-b8fd-c320f6b070aa")]
		public virtual DiagramaWeb DiagramaWeb
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (DiagramaWeb)DslModeling::DomainRoleInfo.GetRolePlayer(this, DiagramaWebDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, DiagramaWebDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access DiagramaWeb of a Entidad
		/// <summary>
		/// Gets DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DiagramaWeb GetDiagramaWeb(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as DiagramaWeb;
		}
		
		/// <summary>
		/// Sets DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetDiagramaWeb(Entidad element, DiagramaWeb newDiagramaWeb)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newDiagramaWeb);
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0xc4fffdc7, 0x8ea2, 0x4388, 0xbc, 0x92, 0x2e, 0x4b, 0xdc, 0x43, 0x70, 0xff);
		
		/// <summary>
		/// DomainRole Entidad
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/Entidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/Entidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "DiagramaWeb", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/Entidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("c4fffdc7-8ea2-4388-bc92-2e4bdc4370ff")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a DiagramaWeb
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(DiagramaWeb element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, DiagramaWebDomainRoleId);
		}
		#endregion
		#region DiagramaWeb link accessor
		/// <summary>
		/// Get the list of DiagramaWebTieneEntidad links to a DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> GetLinksToEntidad ( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb diagramaWebInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>(diagramaWebInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWebDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the DiagramaWebTieneEntidad link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad GetLinkToDiagramaWeb (global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>(entidadInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region DiagramaWebTieneEntidad instance accessors
		
		/// <summary>
		/// Get any DiagramaWebTieneEntidad links between a given DiagramaWeb and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> GetLinks( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>();
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWebDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one DiagramaWebTieneEntidad link between a given DiagramaWeband a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad GetLink( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWebDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadTieneAtributo
	/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("2ab803ae-74a8-4ee9-842e-d1afe77a9ac9")]
	public partial class EntidadTieneAtributo : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadTieneAtributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x2ab803ae, 0x74a8, 0x4ee9, 0x84, 0x2e, 0xd1, 0xaf, 0xe7, 0x7a, 0x9a, 0xc9);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadTieneAtributo link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Atributo to use as the target of the relationship.</param>
		public EntidadTieneAtributo(Entidad source, Atributo target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadTieneAtributo.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadTieneAtributo.AtributoDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneAtributo(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneAtributo(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneAtributo(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneAtributo(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0xeefde135, 0x67ef, 0x47e6, 0x91, 0xb7, 0x2d, 0x94, 0xb1, 0xa9, 0x9f, 0x90);
		
		/// <summary>
		/// DomainRole Entidad
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Entidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Entidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Atributo", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("eefde135-67ef-47e6-91b7-2d94b1a99f90")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Atributo
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(Atributo element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(Atributo element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoDomainRoleId, newEntidad);
		}
		#endregion
		#region Atributo domain role code
		
		/// <summary>
		/// Atributo domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoDomainRoleId = new global::System.Guid(0xff3032d4, 0xf3e1, 0x4a31, 0x95, 0xc0, 0x78, 0x1a, 0xdb, 0xdb, 0x93, 0xa1);
		
		/// <summary>
		/// DomainRole Atributo
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.Atributo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Atributo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Atributo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Atributo.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("ff3032d4-f3e1-4a31-95c0-781adbdb93a1")]
		public virtual Atributo Atributo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Atributo)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Atributo of a Entidad
		/// <summary>
		/// Gets a list of Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Atributo> GetAtributo(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Atributo>, Atributo>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadTieneAtributo links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> GetLinksToAtributo ( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>(entidadInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.EntidadDomainRoleId);
		}
		#endregion
		#region Atributo link accessor
		/// <summary>
		/// Get the EntidadTieneAtributo link to a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo GetLinkToEntidad (global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo atributoInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>(atributoInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.AtributoDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Atributo not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadTieneAtributo instance accessors
		
		/// <summary>
		/// Get any EntidadTieneAtributo links between a given Entidad and a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> GetLinks( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>();
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadTieneAtributo link between a given Entidadand a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo GetLink( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainRelationship Relacion
	/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Relacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("0d83bb08-c405-4538-b654-73c152b86d2a")]
	public partial class Relacion : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// Relacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x0d83bb08, 0xc405, 0x4538, 0xb6, 0x54, 0x73, 0xc1, 0x52, 0xb8, 0x6d, 0x2a);
	
				
		/// <summary>
		/// Constructor
		/// Creates a Relacion link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public Relacion(Entidad source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(Relacion.OrigenEntidadDomainRoleId, source), new DslModeling::RoleAssignment(Relacion.DestinoEntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public Relacion(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public Relacion(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public Relacion(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public Relacion(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region OrigenEntidad domain role code
		
		/// <summary>
		/// OrigenEntidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid OrigenEntidadDomainRoleId = new global::System.Guid(0x2c441897, 0x562f, 0x4cba, 0xa6, 0x87, 0x4c, 0x54, 0x88, 0x77, 0x4f, 0x9e);
		
		/// <summary>
		/// DomainRole OrigenEntidad
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.OrigenEntidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/OrigenEntidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/OrigenEntidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "DestinoEntidad", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/OrigenEntidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("2c441897-562f-4cba-a687-4c5488774f9e")]
		public virtual Entidad OrigenEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, OrigenEntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, OrigenEntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access OrigenEntidad of a Entidad
		/// <summary>
		/// Gets a list of OrigenEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetOrigenEntidad(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, DestinoEntidadDomainRoleId);
		}
		#endregion
		#region DestinoEntidad domain role code
		
		/// <summary>
		/// DestinoEntidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid DestinoEntidadDomainRoleId = new global::System.Guid(0x2424df7c, 0xf223, 0x45cc, 0xac, 0xf4, 0x4d, 0x46, 0x0d, 0xfb, 0x58, 0x6a);
		
		/// <summary>
		/// DomainRole DestinoEntidad
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.DestinoEntidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/DestinoEntidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/DestinoEntidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "OrigenEntidad", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/DestinoEntidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("2424df7c-f223-45cc-acf4-4d460dfb586a")]
		public virtual Entidad DestinoEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, DestinoEntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, DestinoEntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access DestinoEntidad of a Entidad
		/// <summary>
		/// Gets a list of DestinoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetDestinoEntidad(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, OrigenEntidadDomainRoleId);
		}
		#endregion
		#region NombreRelacion domain property code
		
		/// <summary>
		/// NombreRelacion domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreRelacionDomainPropertyId = new global::System.Guid(0x0cbe5a5e, 0x4ae0, 0x4f52, 0xb9, 0x57, 0x83, 0xb0, 0x50, 0x62, 0x7f, 0x8c);
		
		/// <summary>
		/// Storage for NombreRelacion
		/// </summary>
		private global::System.String nombreRelacionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of NombreRelacion domain property.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.Nombre Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/NombreRelacion.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/NombreRelacion.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("0cbe5a5e-4ae0-4f52-b957-83b050627f8c")]
		public global::System.String NombreRelacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombreRelacionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombreRelacionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Relacion.NombreRelacion domain property.
		/// </summary>
		internal sealed partial class NombreRelacionPropertyHandler : DslModeling::DomainPropertyValueHandler<Relacion, global::System.String>
		{
			private NombreRelacionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Relacion.NombreRelacion domain property value handler.
			/// </summary>
			public static readonly NombreRelacionPropertyHandler Instance = new NombreRelacionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Relacion.NombreRelacion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreRelacionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Relacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombreRelacionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Relacion element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombreRelacionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region CardOrigen domain property code
		
		/// <summary>
		/// CardOrigen domain property Id.
		/// </summary>
		public static readonly global::System.Guid CardOrigenDomainPropertyId = new global::System.Guid(0x2c1ceb8c, 0x528d, 0x4d56, 0xb4, 0x2a, 0x01, 0xed, 0xc2, 0x14, 0xb5, 0xcc);
		
		/// <summary>
		/// Storage for CardOrigen
		/// </summary>
		private global::System.String cardOrigenPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of CardOrigen domain property.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.Card Origen
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/CardOrigen.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/CardOrigen.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("2c1ceb8c-528d-4d56-b42a-01edc214b5cc")]
		public global::System.String CardOrigen
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cardOrigenPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				CardOrigenPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Relacion.CardOrigen domain property.
		/// </summary>
		internal sealed partial class CardOrigenPropertyHandler : DslModeling::DomainPropertyValueHandler<Relacion, global::System.String>
		{
			private CardOrigenPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Relacion.CardOrigen domain property value handler.
			/// </summary>
			public static readonly CardOrigenPropertyHandler Instance = new CardOrigenPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Relacion.CardOrigen domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return CardOrigenDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Relacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cardOrigenPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Relacion element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cardOrigenPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region CardDestino domain property code
		
		/// <summary>
		/// CardDestino domain property Id.
		/// </summary>
		public static readonly global::System.Guid CardDestinoDomainPropertyId = new global::System.Guid(0xe96b62ee, 0x3391, 0x440a, 0xb9, 0x9e, 0x87, 0x53, 0x7b, 0xa4, 0x31, 0xcb);
		
		/// <summary>
		/// Storage for CardDestino
		/// </summary>
		private global::System.String cardDestinoPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of CardDestino domain property.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.Card Destino
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/CardDestino.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Relacion/CardDestino.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("e96b62ee-3391-440a-b99e-87537ba431cb")]
		public global::System.String CardDestino
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cardDestinoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				CardDestinoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Relacion.CardDestino domain property.
		/// </summary>
		internal sealed partial class CardDestinoPropertyHandler : DslModeling::DomainPropertyValueHandler<Relacion, global::System.String>
		{
			private CardDestinoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Relacion.CardDestino domain property value handler.
			/// </summary>
			public static readonly CardDestinoPropertyHandler Instance = new CardDestinoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Relacion.CardDestino domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return CardDestinoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Relacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cardDestinoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Relacion element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cardDestinoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region OrigenEntidad link accessor
		/// <summary>
		/// Get the list of Relacion links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion> GetLinksToDestinoEntidad ( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad origenEntidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion>(origenEntidadInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.OrigenEntidadDomainRoleId);
		}
		#endregion
		#region DestinoEntidad link accessor
		/// <summary>
		/// Get the list of Relacion links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion> GetLinksToOrigenEntidad ( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad destinoEntidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion>(destinoEntidadInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.DestinoEntidadDomainRoleId);
		}
		#endregion
		#region Relacion instance accessors
		
		/// <summary>
		/// Get any Relacion links between a given Entidad and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion> GetLinks( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion>();
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.OrigenEntidadDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion link in links )
			{
				if ( target.Equals(link.DestinoEntidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one Relacion link between a given Entidadand a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion GetLink( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.OrigenEntidadDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion link in links )
			{
				if ( target.Equals(link.DestinoEntidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainRelationship DiagramaWebTieneEstiloPortal
	/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("fda28509-cc6f-45bb-9c9c-2f6fff3f94c9")]
	public partial class DiagramaWebTieneEstiloPortal : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// DiagramaWebTieneEstiloPortal domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xfda28509, 0xcc6f, 0x45bb, 0x9c, 0x9c, 0x2f, 0x6f, 0xff, 0x3f, 0x94, 0xc9);
	
				
		/// <summary>
		/// Constructor
		/// Creates a DiagramaWebTieneEstiloPortal link in the same Partition as the given DiagramaWeb
		/// </summary>
		/// <param name="source">DiagramaWeb to use as the source of the relationship.</param>
		/// <param name="target">EstiloPortal to use as the target of the relationship.</param>
		public DiagramaWebTieneEstiloPortal(DiagramaWeb source, EstiloPortal target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(DiagramaWebTieneEstiloPortal.DiagramaWebDomainRoleId, source), new DslModeling::RoleAssignment(DiagramaWebTieneEstiloPortal.EstiloPortalDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DiagramaWebTieneEstiloPortal(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DiagramaWebTieneEstiloPortal(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DiagramaWebTieneEstiloPortal(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DiagramaWebTieneEstiloPortal(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region DiagramaWeb domain role code
		
		/// <summary>
		/// DiagramaWeb domain role Id.
		/// </summary>
		public static readonly global::System.Guid DiagramaWebDomainRoleId = new global::System.Guid(0x42e9ac22, 0x424a, 0x47d0, 0xbc, 0x1e, 0x57, 0xff, 0x14, 0xb9, 0xda, 0x0a);
		
		/// <summary>
		/// DomainRole DiagramaWeb
		/// Description for
		/// UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.DiagramaWeb
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal/DiagramaWeb.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal/DiagramaWeb.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "EstiloPortal", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal/DiagramaWeb.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("42e9ac22-424a-47d0-bc1e-57ff14b9da0a")]
		public virtual DiagramaWeb DiagramaWeb
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (DiagramaWeb)DslModeling::DomainRoleInfo.GetRolePlayer(this, DiagramaWebDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, DiagramaWebDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access DiagramaWeb of a EstiloPortal
		/// <summary>
		/// Gets DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DiagramaWeb GetDiagramaWeb(EstiloPortal element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EstiloPortalDomainRoleId) as DiagramaWeb;
		}
		
		/// <summary>
		/// Sets DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetDiagramaWeb(EstiloPortal element, DiagramaWeb newDiagramaWeb)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EstiloPortalDomainRoleId, newDiagramaWeb);
		}
		#endregion
		#region EstiloPortal domain role code
		
		/// <summary>
		/// EstiloPortal domain role Id.
		/// </summary>
		public static readonly global::System.Guid EstiloPortalDomainRoleId = new global::System.Guid(0xb7511ad4, 0x4683, 0x4b30, 0xa8, 0x4f, 0x02, 0x52, 0xd6, 0x89, 0xba, 0xf6);
		
		/// <summary>
		/// DomainRole EstiloPortal
		/// Description for
		/// UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.EstiloPortal
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal/EstiloPortal.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal/EstiloPortal.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "DiagramaWeb", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal/EstiloPortal.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("b7511ad4-4683-4b30-a84f-0252d689baf6")]
		public virtual EstiloPortal EstiloPortal
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (EstiloPortal)DslModeling::DomainRoleInfo.GetRolePlayer(this, EstiloPortalDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EstiloPortalDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access EstiloPortal of a DiagramaWeb
		/// <summary>
		/// Gets EstiloPortal.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static EstiloPortal GetEstiloPortal(DiagramaWeb element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, DiagramaWebDomainRoleId) as EstiloPortal;
		}
		
		/// <summary>
		/// Sets EstiloPortal.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEstiloPortal(DiagramaWeb element, EstiloPortal newEstiloPortal)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, DiagramaWebDomainRoleId, newEstiloPortal);
		}
		#endregion
		#region DiagramaWeb link accessor
		/// <summary>
		/// Get the DiagramaWebTieneEstiloPortal link to a DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal GetLinkToEstiloPortal (global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb diagramaWebInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal>(diagramaWebInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.DiagramaWebDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of DiagramaWeb not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EstiloPortal link accessor
		/// <summary>
		/// Get the DiagramaWebTieneEstiloPortal link to a EstiloPortal.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal GetLinkToDiagramaWeb (global::UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal estiloPortalInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal>(estiloPortalInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.EstiloPortalDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of EstiloPortal not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region DiagramaWebTieneEstiloPortal instance accessors
		
		/// <summary>
		/// Get any DiagramaWebTieneEstiloPortal links between a given DiagramaWeb and a EstiloPortal.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal> GetLinks( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal>();
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.DiagramaWebDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal link in links )
			{
				if ( target.Equals(link.EstiloPortal) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one DiagramaWebTieneEstiloPortal link between a given DiagramaWeband a EstiloPortal.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal GetLink( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.DiagramaWebDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal link in links )
			{
				if ( target.Equals(link.EstiloPortal) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadTieneEstiloPagina
	/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("ba6e6e02-4b15-4fbb-a32c-daeec94b621d")]
	public partial class EntidadTieneEstiloPagina : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadTieneEstiloPagina domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xba6e6e02, 0x4b15, 0x4fbb, 0xa3, 0x2c, 0xda, 0xee, 0xc9, 0x4b, 0x62, 0x1d);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadTieneEstiloPagina link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">EstiloPagina to use as the target of the relationship.</param>
		public EntidadTieneEstiloPagina(Entidad source, EstiloPagina target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadTieneEstiloPagina.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadTieneEstiloPagina.EstiloPaginaDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneEstiloPagina(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneEstiloPagina(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneEstiloPagina(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneEstiloPagina(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x8c77841a, 0xe15b, 0x437f, 0x88, 0xb7, 0x34, 0x35, 0x4e, 0x35, 0xf2, 0xc0);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina/Entidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina/Entidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "EstiloPagina", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("8c77841a-e15b-437f-88b7-34354e35f2c0")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a EstiloPagina
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(EstiloPagina element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EstiloPaginaDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(EstiloPagina element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EstiloPaginaDomainRoleId, newEntidad);
		}
		#endregion
		#region EstiloPagina domain role code
		
		/// <summary>
		/// EstiloPagina domain role Id.
		/// </summary>
		public static readonly global::System.Guid EstiloPaginaDomainRoleId = new global::System.Guid(0x844ccbaf, 0xe8eb, 0x4718, 0xae, 0x39, 0x2a, 0xb5, 0x6f, 0xad, 0x18, 0xd5);
		
		/// <summary>
		/// DomainRole EstiloPagina
		/// Description for
		/// UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EstiloPagina
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina/EstiloPagina.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina/EstiloPagina.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina/EstiloPagina.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("844ccbaf-e8eb-4718-ae39-2ab56fad18d5")]
		public virtual EstiloPagina EstiloPagina
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (EstiloPagina)DslModeling::DomainRoleInfo.GetRolePlayer(this, EstiloPaginaDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EstiloPaginaDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access EstiloPagina of a Entidad
		/// <summary>
		/// Gets EstiloPagina.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static EstiloPagina GetEstiloPagina(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as EstiloPagina;
		}
		
		/// <summary>
		/// Sets EstiloPagina.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEstiloPagina(Entidad element, EstiloPagina newEstiloPagina)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newEstiloPagina);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the EntidadTieneEstiloPagina link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina GetLinkToEstiloPagina (global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina>(entidadInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EstiloPagina link accessor
		/// <summary>
		/// Get the EntidadTieneEstiloPagina link to a EstiloPagina.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina GetLinkToEntidad (global::UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina estiloPaginaInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina>(estiloPaginaInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EstiloPaginaDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of EstiloPagina not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadTieneEstiloPagina instance accessors
		
		/// <summary>
		/// Get any EntidadTieneEstiloPagina links between a given Entidad and a EstiloPagina.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina> GetLinks( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina>();
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina link in links )
			{
				if ( target.Equals(link.EstiloPagina) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadTieneEstiloPagina link between a given Entidadand a EstiloPagina.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina GetLink( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina link in links )
			{
				if ( target.Equals(link.EstiloPagina) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
