//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainClass DiagramaWeb
	/// The root in which all other elements are embedded. Appears as a diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("695c01ea-e79f-4eaa-9cbd-d9ef873a216b")]
	public partial class DiagramaWeb : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// DiagramaWeb domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x695c01ea, 0xe79f, 0x4eaa, 0x9c, 0xbd, 0xd9, 0xef, 0x87, 0x3a, 0x21, 0x6b);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DiagramaWeb(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DiagramaWeb(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Titulo domain property code
		
		/// <summary>
		/// Titulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid TituloDomainPropertyId = new global::System.Guid(0xcb7a9f9f, 0xfb34, 0x4665, 0xb3, 0x7b, 0xca, 0x40, 0xde, 0xba, 0x8c, 0xb3);
		
		/// <summary>
		/// Storage for Titulo
		/// </summary>
		private global::System.String tituloPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Titulo domain property.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb.Titulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb/Titulo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb/Titulo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("cb7a9f9f-fb34-4665-b37b-ca40deba8cb3")]
		public global::System.String Titulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tituloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TituloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the DiagramaWeb.Titulo domain property.
		/// </summary>
		internal sealed partial class TituloPropertyHandler : DslModeling::DomainPropertyValueHandler<DiagramaWeb, global::System.String>
		{
			private TituloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the DiagramaWeb.Titulo domain property value handler.
			/// </summary>
			public static readonly TituloPropertyHandler Instance = new TituloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the DiagramaWeb.Titulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TituloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(DiagramaWeb element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tituloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(DiagramaWeb element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tituloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Entidad.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWeb
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWebDomainRoleId);
			}
		}
		#endregion
		#region EstiloPortal opposite domain role accessor
		/// <summary>
		/// Gets or sets EstiloPortal.
		/// Description for
		/// UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.DiagramaWeb
		/// </summary>
		public virtual EstiloPortal EstiloPortal
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.DiagramaWebDomainRoleId) as EstiloPortal;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.DiagramaWebDomainRoleId, value);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad sourceEntidad1 = sourceElement as global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad;
			if (sourceEntidad1 != null)
			{
				// Create link for path DiagramaWebTieneEntidad.Entidad
				this.Entidad.Add(sourceEntidad1);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad sourceEntidad1 = sourceElement as global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad;
			if (sourceEntidad1 != null)
			{
				// Delete link for path DiagramaWebTieneEntidad.Entidad
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.GetLinks((global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb)this, sourceEntidad1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWebDomainRoleId, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.EntidadDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainClass Entidad
	/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Entidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Entidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Entidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("e68282dc-d965-45d5-8312-2957e5b5e5e4")]
	public partial class Entidad : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Entidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe68282dc, 0xd965, 0x45d5, 0x83, 0x12, 0x29, 0x57, 0xe5, 0xb5, 0xe5, 0xe4);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Nombre domain property code
		
		/// <summary>
		/// Nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreDomainPropertyId = new global::System.Guid(0xfb3fcd23, 0x7fd7, 0x4211, 0x8a, 0xc3, 0x7b, 0x06, 0xc9, 0x5d, 0x80, 0x4e);
		
		/// <summary>
		/// Storage for Nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Nombre domain property.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Entidad.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Entidad/Nombre.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Entidad/Nombre.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("fb3fcd23-7fd7-4211-8ac3-7b06c95d804e")]
		public global::System.String Nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Entidad.Nombre domain property.
		/// </summary>
		internal sealed partial class NombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Entidad, global::System.String>
		{
			private NombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Entidad.Nombre domain property value handler.
			/// </summary>
			public static readonly NombrePropertyHandler Instance = new NombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Entidad.Nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Entidad element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Entidad element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region DiagramaWeb opposite domain role accessor
		/// <summary>
		/// Gets or sets DiagramaWeb.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.Entidad
		/// </summary>
		public virtual DiagramaWeb DiagramaWeb
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.EntidadDomainRoleId) as DiagramaWeb;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.EntidadDomainRoleId, value);
			}
		}
		#endregion
		#region Atributo opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Atributo.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Atributo> Atributo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Atributo>, Atributo>(global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.EntidadDomainRoleId);
			}
		}
		#endregion
		#region DestinoEntidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of DestinoEntidad.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.OrigenEntidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> DestinoEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.OrigenEntidadDomainRoleId);
			}
		}
		#endregion
		#region OrigenEntidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of OrigenEntidad.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.DestinoEntidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> OrigenEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.JGAJPTJJLProyectoIPS.Relacion.DestinoEntidadDomainRoleId);
			}
		}
		#endregion
		#region EstiloPagina opposite domain role accessor
		/// <summary>
		/// Gets or sets EstiloPagina.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.Entidad
		/// </summary>
		public virtual EstiloPagina EstiloPagina
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EntidadDomainRoleId) as EstiloPagina;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EntidadDomainRoleId, value);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo sourceAtributo1 = sourceElement as global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo;
			if (sourceAtributo1 != null)
			{
				// Create link for path EntidadTieneAtributo.Atributo
				this.Atributo.Add(sourceAtributo1);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo sourceAtributo1 = sourceElement as global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo;
			if (sourceAtributo1 != null)
			{
				// Delete link for path EntidadTieneAtributo.Atributo
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.GetLinks((global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad)this, sourceAtributo1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.EntidadDomainRoleId, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.AtributoDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainClass Atributo
	/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Atributo
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Atributo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Atributo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("2dd5eb38-9189-40bb-9463-56acf25bf9b7")]
	public partial class Atributo : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Atributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x2dd5eb38, 0x9189, 0x40bb, 0x94, 0x63, 0x56, 0xac, 0xf2, 0x5b, 0xf9, 0xb7);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Atributo(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Atributo(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Nombre domain property code
		
		/// <summary>
		/// Nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreDomainPropertyId = new global::System.Guid(0x80a1c384, 0xe95a, 0x4644, 0xbe, 0x16, 0xd7, 0xc2, 0x18, 0xdd, 0xd2, 0xeb);
		
		/// <summary>
		/// Storage for Nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Nombre domain property.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Atributo.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Atributo/Nombre.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Atributo/Nombre.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("80a1c384-e95a-4644-be16-d7c218ddd2eb")]
		public global::System.String Nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.Nombre domain property.
		/// </summary>
		internal sealed partial class NombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, global::System.String>
		{
			private NombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.Nombre domain property value handler.
			/// </summary>
			public static readonly NombrePropertyHandler Instance = new NombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.Nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Tipo domain property code
		
		/// <summary>
		/// Tipo domain property Id.
		/// </summary>
		public static readonly global::System.Guid TipoDomainPropertyId = new global::System.Guid(0xb72c54a8, 0x8ae3, 0x4d45, 0x82, 0x12, 0x40, 0x8f, 0xe2, 0x25, 0x0a, 0xcf);
		
		/// <summary>
		/// Storage for Tipo
		/// </summary>
		private TipoDatoEnum tipoPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of Tipo domain property.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.Atributo.Tipo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Atributo/Tipo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Atributo/Tipo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("b72c54a8-8ae3-4d45-8212-408fe2250acf")]
		public TipoDatoEnum Tipo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tipoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TipoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.Tipo domain property.
		/// </summary>
		internal sealed partial class TipoPropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, TipoDatoEnum>
		{
			private TipoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.Tipo domain property value handler.
			/// </summary>
			public static readonly TipoPropertyHandler Instance = new TipoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.Tipo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TipoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed TipoDatoEnum GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tipoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, TipoDatoEnum newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				TipoDatoEnum oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tipoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region esClaveprimaria domain property code
		
		/// <summary>
		/// esClaveprimaria domain property Id.
		/// </summary>
		public static readonly global::System.Guid esClaveprimariaDomainPropertyId = new global::System.Guid(0x47333426, 0x4fd3, 0x47db, 0x8e, 0xfd, 0x1a, 0x3b, 0x03, 0x57, 0x89, 0x1e);
		
		/// <summary>
		/// Storage for esClaveprimaria
		/// </summary>
		private global::System.Boolean esClaveprimariaPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of esClaveprimaria domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.Atributo.Es Claveprimaria
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.Atributo/esClaveprimaria.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.Atributo/esClaveprimaria.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("47333426-4fd3-47db-8efd-1a3b0357891e")]
		public global::System.Boolean esClaveprimaria
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return esClaveprimariaPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				esClaveprimariaPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.esClaveprimaria domain property.
		/// </summary>
		internal sealed partial class esClaveprimariaPropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, global::System.Boolean>
		{
			private esClaveprimariaPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.esClaveprimaria domain property value handler.
			/// </summary>
			public static readonly esClaveprimariaPropertyHandler Instance = new esClaveprimariaPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.esClaveprimaria domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return esClaveprimariaDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Boolean GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.esClaveprimariaPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, global::System.Boolean newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Boolean oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.esClaveprimariaPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.Atributo
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.AtributoDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.AtributoDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainClass EstiloPortal
	/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("6807fc0c-f2fd-41d3-aaa4-d8acecb4426c")]
	public partial class EstiloPortal : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// EstiloPortal domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x6807fc0c, 0xf2fd, 0x41d3, 0xaa, 0xa4, 0xd8, 0xac, 0xec, 0xb4, 0x42, 0x6c);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EstiloPortal(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EstiloPortal(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Titulo domain property code
		
		/// <summary>
		/// Titulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid TituloDomainPropertyId = new global::System.Guid(0xc55c5203, 0x3485, 0x4292, 0x9c, 0x07, 0xb2, 0x99, 0x9b, 0x33, 0x1d, 0x7d);
		
		/// <summary>
		/// Storage for Titulo
		/// </summary>
		private global::System.String tituloPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Titulo domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal.Titulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/Titulo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/Titulo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("c55c5203-3485-4292-9c07-b2999b331d7d")]
		public global::System.String Titulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tituloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TituloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPortal.Titulo domain property.
		/// </summary>
		internal sealed partial class TituloPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPortal, global::System.String>
		{
			private TituloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPortal.Titulo domain property value handler.
			/// </summary>
			public static readonly TituloPropertyHandler Instance = new TituloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPortal.Titulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TituloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EstiloPortal element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tituloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPortal element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tituloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region ColorFondo domain property code
		
		/// <summary>
		/// ColorFondo domain property Id.
		/// </summary>
		public static readonly global::System.Guid ColorFondoDomainPropertyId = new global::System.Guid(0x8492f4f7, 0x24f3, 0x4a0a, 0xa0, 0x33, 0xd5, 0x2c, 0x3b, 0xd3, 0x80, 0x4e);
		
		/// <summary>
		/// Storage for ColorFondo
		/// </summary>
		private global::System.String colorFondoPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of ColorFondo domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal.Color Fondo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/ColorFondo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/ColorFondo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("8492f4f7-24f3-4a0a-a033-d52c3bd3804e")]
		public global::System.String ColorFondo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return colorFondoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				ColorFondoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPortal.ColorFondo domain property.
		/// </summary>
		internal sealed partial class ColorFondoPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPortal, global::System.String>
		{
			private ColorFondoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPortal.ColorFondo domain property value handler.
			/// </summary>
			public static readonly ColorFondoPropertyHandler Instance = new ColorFondoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPortal.ColorFondo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return ColorFondoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EstiloPortal element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.colorFondoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPortal element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.colorFondoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region ColorTitulo domain property code
		
		/// <summary>
		/// ColorTitulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid ColorTituloDomainPropertyId = new global::System.Guid(0xb3115dae, 0xf5e4, 0x4111, 0xa9, 0x36, 0x3b, 0xed, 0x70, 0x27, 0xaa, 0xa2);
		
		/// <summary>
		/// Storage for ColorTitulo
		/// </summary>
		private global::System.String colorTituloPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of ColorTitulo domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal.Color Titulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/ColorTitulo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/ColorTitulo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("b3115dae-f5e4-4111-a936-3bed7027aaa2")]
		public global::System.String ColorTitulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return colorTituloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				ColorTituloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPortal.ColorTitulo domain property.
		/// </summary>
		internal sealed partial class ColorTituloPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPortal, global::System.String>
		{
			private ColorTituloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPortal.ColorTitulo domain property value handler.
			/// </summary>
			public static readonly ColorTituloPropertyHandler Instance = new ColorTituloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPortal.ColorTitulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return ColorTituloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EstiloPortal element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.colorTituloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPortal element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.colorTituloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region TipoLetra domain property code
		
		/// <summary>
		/// TipoLetra domain property Id.
		/// </summary>
		public static readonly global::System.Guid TipoLetraDomainPropertyId = new global::System.Guid(0x82142e95, 0x6d46, 0x4ed6, 0x97, 0xbf, 0x6b, 0x18, 0xf1, 0xa6, 0x07, 0xbb);
		
		/// <summary>
		/// Storage for TipoLetra
		/// </summary>
		private global::System.String tipoLetraPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of TipoLetra domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal.Tipo Letra
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/TipoLetra.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/TipoLetra.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("82142e95-6d46-4ed6-97bf-6b18f1a607bb")]
		public global::System.String TipoLetra
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tipoLetraPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TipoLetraPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPortal.TipoLetra domain property.
		/// </summary>
		internal sealed partial class TipoLetraPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPortal, global::System.String>
		{
			private TipoLetraPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPortal.TipoLetra domain property value handler.
			/// </summary>
			public static readonly TipoLetraPropertyHandler Instance = new TipoLetraPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPortal.TipoLetra domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TipoLetraDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EstiloPortal element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tipoLetraPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPortal element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tipoLetraPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region TamanoLetra domain property code
		
		/// <summary>
		/// TamanoLetra domain property Id.
		/// </summary>
		public static readonly global::System.Guid TamanoLetraDomainPropertyId = new global::System.Guid(0x9381ca02, 0x8968, 0x4e56, 0xae, 0x3b, 0x99, 0xd5, 0x90, 0xec, 0xd6, 0x7a);
		
		/// <summary>
		/// Storage for TamanoLetra
		/// </summary>
		private global::System.Int32 tamanoLetraPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of TamanoLetra domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal.Tamano Letra
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/TamanoLetra.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/TamanoLetra.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("9381ca02-8968-4e56-ae3b-99d590ecd67a")]
		public global::System.Int32 TamanoLetra
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tamanoLetraPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TamanoLetraPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPortal.TamanoLetra domain property.
		/// </summary>
		internal sealed partial class TamanoLetraPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPortal, global::System.Int32>
		{
			private TamanoLetraPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPortal.TamanoLetra domain property value handler.
			/// </summary>
			public static readonly TamanoLetraPropertyHandler Instance = new TamanoLetraPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPortal.TamanoLetra domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TamanoLetraDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Int32 GetValue(EstiloPortal element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tamanoLetraPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPortal element, global::System.Int32 newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Int32 oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tamanoLetraPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Alineacion domain property code
		
		/// <summary>
		/// Alineacion domain property Id.
		/// </summary>
		public static readonly global::System.Guid AlineacionDomainPropertyId = new global::System.Guid(0x86cbb140, 0xb23d, 0x4d9a, 0x8f, 0x18, 0xd7, 0xd1, 0x23, 0x43, 0x5f, 0x46);
		
		/// <summary>
		/// Storage for Alineacion
		/// </summary>
		private global::System.String alineacionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Alineacion domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal.Alineacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/Alineacion.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPortal/Alineacion.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("86cbb140-b23d-4d9a-8f18-d7d123435f46")]
		public global::System.String Alineacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return alineacionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				AlineacionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPortal.Alineacion domain property.
		/// </summary>
		internal sealed partial class AlineacionPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPortal, global::System.String>
		{
			private AlineacionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPortal.Alineacion domain property value handler.
			/// </summary>
			public static readonly AlineacionPropertyHandler Instance = new AlineacionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPortal.Alineacion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return AlineacionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EstiloPortal element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.alineacionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPortal element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.alineacionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region DiagramaWeb opposite domain role accessor
		/// <summary>
		/// Gets or sets DiagramaWeb.
		/// Description for
		/// UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.EstiloPortal
		/// </summary>
		public virtual DiagramaWeb DiagramaWeb
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.EstiloPortalDomainRoleId) as DiagramaWeb;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEstiloPortal.EstiloPortalDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainClass EstiloPagina
	/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("1c337f5a-a41d-4c17-8952-b5891188310e")]
	public partial class EstiloPagina : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// EstiloPagina domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x1c337f5a, 0xa41d, 0x4c17, 0x89, 0x52, 0xb5, 0x89, 0x11, 0x88, 0x31, 0x0e);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EstiloPagina(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EstiloPagina(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Color domain property code
		
		/// <summary>
		/// Color domain property Id.
		/// </summary>
		public static readonly global::System.Guid ColorDomainPropertyId = new global::System.Guid(0x0987ecbc, 0xaa53, 0x4168, 0xa2, 0x1e, 0x01, 0x96, 0xf7, 0x9e, 0x7e, 0xab);
		
		/// <summary>
		/// Storage for Color
		/// </summary>
		private global::System.String colorPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Color domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina.Color
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina/Color.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina/Color.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("0987ecbc-aa53-4168-a21e-0196f79e7eab")]
		public global::System.String Color
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return colorPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				ColorPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPagina.Color domain property.
		/// </summary>
		internal sealed partial class ColorPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPagina, global::System.String>
		{
			private ColorPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPagina.Color domain property value handler.
			/// </summary>
			public static readonly ColorPropertyHandler Instance = new ColorPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPagina.Color domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return ColorDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EstiloPagina element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.colorPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPagina element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.colorPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region TipoLetra domain property code
		
		/// <summary>
		/// TipoLetra domain property Id.
		/// </summary>
		public static readonly global::System.Guid TipoLetraDomainPropertyId = new global::System.Guid(0xf638a893, 0xb901, 0x4949, 0xa7, 0x91, 0xf4, 0xeb, 0x8d, 0x19, 0x1d, 0xd4);
		
		/// <summary>
		/// Storage for TipoLetra
		/// </summary>
		private global::System.String tipoLetraPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of TipoLetra domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina.Tipo Letra
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina/TipoLetra.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina/TipoLetra.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("f638a893-b901-4949-a791-f4eb8d191dd4")]
		public global::System.String TipoLetra
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tipoLetraPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TipoLetraPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPagina.TipoLetra domain property.
		/// </summary>
		internal sealed partial class TipoLetraPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPagina, global::System.String>
		{
			private TipoLetraPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPagina.TipoLetra domain property value handler.
			/// </summary>
			public static readonly TipoLetraPropertyHandler Instance = new TipoLetraPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPagina.TipoLetra domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TipoLetraDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EstiloPagina element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tipoLetraPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPagina element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tipoLetraPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region TamanoLetra domain property code
		
		/// <summary>
		/// TamanoLetra domain property Id.
		/// </summary>
		public static readonly global::System.Guid TamanoLetraDomainPropertyId = new global::System.Guid(0x623607df, 0x57b8, 0x49e9, 0xa5, 0x43, 0x24, 0x9e, 0x66, 0x67, 0x25, 0xe7);
		
		/// <summary>
		/// Storage for TamanoLetra
		/// </summary>
		private global::System.Int32 tamanoLetraPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of TamanoLetra domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina.Tamano Letra
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina/TamanoLetra.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina/TamanoLetra.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("623607df-57b8-49e9-a543-249e666725e7")]
		public global::System.Int32 TamanoLetra
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tamanoLetraPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TamanoLetraPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPagina.TamanoLetra domain property.
		/// </summary>
		internal sealed partial class TamanoLetraPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPagina, global::System.Int32>
		{
			private TamanoLetraPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPagina.TamanoLetra domain property value handler.
			/// </summary>
			public static readonly TamanoLetraPropertyHandler Instance = new TamanoLetraPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPagina.TamanoLetra domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TamanoLetraDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Int32 GetValue(EstiloPagina element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tamanoLetraPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPagina element, global::System.Int32 newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Int32 oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tamanoLetraPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Alineacion domain property code
		
		/// <summary>
		/// Alineacion domain property Id.
		/// </summary>
		public static readonly global::System.Guid AlineacionDomainPropertyId = new global::System.Guid(0xff924661, 0x6613, 0x4eea, 0xaf, 0xd1, 0x92, 0x7e, 0xc6, 0xf0, 0x99, 0xc4);
		
		/// <summary>
		/// Storage for Alineacion
		/// </summary>
		private global::System.String alineacionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Alineacion domain property.
		/// Description for UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina.Alineacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina/Alineacion.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EstiloPagina/Alineacion.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("ff924661-6613-4eea-afd1-927ec6f099c4")]
		public global::System.String Alineacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return alineacionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				AlineacionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EstiloPagina.Alineacion domain property.
		/// </summary>
		internal sealed partial class AlineacionPropertyHandler : DslModeling::DomainPropertyValueHandler<EstiloPagina, global::System.String>
		{
			private AlineacionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EstiloPagina.Alineacion domain property value handler.
			/// </summary>
			public static readonly AlineacionPropertyHandler Instance = new AlineacionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EstiloPagina.Alineacion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return AlineacionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EstiloPagina element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.alineacionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EstiloPagina element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.alineacionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for
		/// UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EstiloPagina
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EstiloPaginaDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneEstiloPagina.EstiloPaginaDomainRoleId, value);
			}
		}
		#endregion
	}
}
