//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainRelationship DiagramaWebTieneEntidad
	/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("b20186c3-98c3-4932-a9f5-9c00ae76b0ce")]
	public partial class DiagramaWebTieneEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// DiagramaWebTieneEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xb20186c3, 0x98c3, 0x4932, 0xa9, 0xf5, 0x9c, 0x00, 0xae, 0x76, 0xb0, 0xce);
	
				
		/// <summary>
		/// Constructor
		/// Creates a DiagramaWebTieneEntidad link in the same Partition as the given DiagramaWeb
		/// </summary>
		/// <param name="source">DiagramaWeb to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public DiagramaWebTieneEntidad(DiagramaWeb source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(DiagramaWebTieneEntidad.DiagramaWebDomainRoleId, source), new DslModeling::RoleAssignment(DiagramaWebTieneEntidad.EntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DiagramaWebTieneEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DiagramaWebTieneEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DiagramaWebTieneEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DiagramaWebTieneEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region DiagramaWeb domain role code
		
		/// <summary>
		/// DiagramaWeb domain role Id.
		/// </summary>
		public static readonly global::System.Guid DiagramaWebDomainRoleId = new global::System.Guid(0xf329662f, 0x0004, 0x4d33, 0xb8, 0xfd, 0xc3, 0x20, 0xf6, 0xb0, 0x70, 0xaa);
		
		/// <summary>
		/// DomainRole DiagramaWeb
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWeb
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/DiagramaWeb.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/DiagramaWeb.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/DiagramaWeb.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("f329662f-0004-4d33-b8fd-c320f6b070aa")]
		public virtual DiagramaWeb DiagramaWeb
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (DiagramaWeb)DslModeling::DomainRoleInfo.GetRolePlayer(this, DiagramaWebDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, DiagramaWebDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access DiagramaWeb of a Entidad
		/// <summary>
		/// Gets DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DiagramaWeb GetDiagramaWeb(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as DiagramaWeb;
		}
		
		/// <summary>
		/// Sets DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetDiagramaWeb(Entidad element, DiagramaWeb newDiagramaWeb)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newDiagramaWeb);
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0xc4fffdc7, 0x8ea2, 0x4388, 0xbc, 0x92, 0x2e, 0x4b, 0xdc, 0x43, 0x70, 0xff);
		
		/// <summary>
		/// DomainRole Entidad
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/Entidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/Entidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "DiagramaWeb", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad/Entidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("c4fffdc7-8ea2-4388-bc92-2e4bdc4370ff")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a DiagramaWeb
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(DiagramaWeb element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, DiagramaWebDomainRoleId);
		}
		#endregion
		#region DiagramaWeb link accessor
		/// <summary>
		/// Get the list of DiagramaWebTieneEntidad links to a DiagramaWeb.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> GetLinksToEntidad ( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb diagramaWebInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>(diagramaWebInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWebDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the DiagramaWebTieneEntidad link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad GetLinkToDiagramaWeb (global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>(entidadInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region DiagramaWebTieneEntidad instance accessors
		
		/// <summary>
		/// Get any DiagramaWebTieneEntidad links between a given DiagramaWeb and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> GetLinks( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>();
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWebDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one DiagramaWebTieneEntidad link between a given DiagramaWeband a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad GetLink( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWeb source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad.DiagramaWebDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.DiagramaWebTieneEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadTieneAtributo
	/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("2ab803ae-74a8-4ee9-842e-d1afe77a9ac9")]
	public partial class EntidadTieneAtributo : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadTieneAtributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x2ab803ae, 0x74a8, 0x4ee9, 0x84, 0x2e, 0xd1, 0xaf, 0xe7, 0x7a, 0x9a, 0xc9);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadTieneAtributo link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Atributo to use as the target of the relationship.</param>
		public EntidadTieneAtributo(Entidad source, Atributo target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadTieneAtributo.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadTieneAtributo.AtributoDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneAtributo(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneAtributo(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneAtributo(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneAtributo(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0xeefde135, 0x67ef, 0x47e6, 0x91, 0xb7, 0x2d, 0x94, 0xb1, 0xa9, 0x9f, 0x90);
		
		/// <summary>
		/// DomainRole Entidad
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Entidad.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Entidad.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Atributo", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("eefde135-67ef-47e6-91b7-2d94b1a99f90")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Atributo
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(Atributo element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(Atributo element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoDomainRoleId, newEntidad);
		}
		#endregion
		#region Atributo domain role code
		
		/// <summary>
		/// Atributo domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoDomainRoleId = new global::System.Guid(0xff3032d4, 0xf3e1, 0x4a31, 0x95, 0xc0, 0x78, 0x1a, 0xdb, 0xdb, 0x93, 0xa1);
		
		/// <summary>
		/// DomainRole Atributo
		/// Descripción de UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.Atributo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Atributo.DisplayName", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Atributo.Description", typeof(global::UPM_IPS.JGAJPTJJLProyectoIPS.PracticaDERADomainModel), "UPM_IPS.JGAJPTJJLProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo/Atributo.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("ff3032d4-f3e1-4a31-95c0-781adbdb93a1")]
		public virtual Atributo Atributo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Atributo)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Atributo of a Entidad
		/// <summary>
		/// Gets a list of Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Atributo> GetAtributo(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Atributo>, Atributo>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadTieneAtributo links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> GetLinksToAtributo ( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>(entidadInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.EntidadDomainRoleId);
		}
		#endregion
		#region Atributo link accessor
		/// <summary>
		/// Get the EntidadTieneAtributo link to a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo GetLinkToEntidad (global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo atributoInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>(atributoInstance, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.AtributoDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Atributo not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadTieneAtributo instance accessors
		
		/// <summary>
		/// Get any EntidadTieneAtributo links between a given Entidad and a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> GetLinks( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>();
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadTieneAtributo link between a given Entidadand a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo GetLink( global::UPM_IPS.JGAJPTJJLProyectoIPS.Entidad source, global::UPM_IPS.JGAJPTJJLProyectoIPS.Atributo target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo>(source, global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.JGAJPTJJLProyectoIPS.EntidadTieneAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
