//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "JGAJPTJJL_ProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"JGAJPTJJLProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID PracticaDERADiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PracticaDERACommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID PracticaDERAExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PracticaDERACommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewPracticaDERAExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PracticaDERACommandSetId), 0x0001);
	
		// Package identifier
		public const string PracticaDERAPackageId = "1e318e2f-e85f-406a-a13b-ab09f10f5242";
		
		// Editor factory identifier
		public const string PracticaDERAEditorFactoryId = "72c70a48-a248-4138-abea-3ffc75fe2957";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string PracticaDERAModelExplorerToolWindowId = "238c954e-70bd-444a-b47b-7a8e487b493e";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.JGAJPTJJLProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string PracticaDERACommandSetId = "e80029e1-8e6d-4ef2-ae91-d005cb4964ab";
	}
}